from datetime import date

# firebase
FIREBASE_CONFIG = {
    'apiKey': "AIzaSyCtotU0H3hBXwq-Z3-29HSUHKin2M-JdDA",
    'authDomain': "fintracker-ec2ae.firebaseapp.com",
    'databaseURL': 'https://fintracker-ec2ae-default-rtdb.firebaseio.com/',
    'projectId': "fintracker-ec2ae",
    'storageBucket': "fintracker-ec2ae.appspot.com",
    'messagingSenderId': "281971152933",
    'appId': "1:281971152933:web:2fcd7568723b378846c7cc",
    'measurementId': "G-8Z1P4NZ1TJ"
}

# ids======================================================================

# fonts
DEFAULT_FONT_THEME_ID = "Default Font"
HEADER_FONT_THEME_ID = "Header Font"

# themes
DEFAULT_THEME_ID = "Default Theme"
GREEN_TEXT_COLOR_THEME_ID = "Green Text"
RED_TEXT_COLOR_THEME_ID = "Red Text"
RED_BTN_COLOR_THEME_ID = "Red Button"

# loading window
LOADING_WINDOW_ID = "Loading Window"

# dialog
DIALOG_WINDOW_ID = "Dialog Window"
DIALOG_CONFIRMATION_BTN_ID = "Dialog Window Confirmation Button"
DIALOG_THEME_ID = "Dialog Theme"

# option window
OPTION_WINDOW_ID = "Options Window"
OPTION_WINDOW_TICKER_INPUT_ID = "Options Ticker Input"
OPTION_WINDOW_SEARCH_BTN_ID = "Options Search Button"
OPTION_WINDOW_OPTION_TYPE_COMBO_ID = "Options Type Combo"
OPTION_WINDOW_DATE_COMBO_ID = "Options Date Combo"
OPTION_WINDOW_SEARCH_CONTRACT_BTN_ID = "Options Contract Search Button"
OPTION_TABLE_ID = "Options Table"

# trade input window
TRADE_INPUT_WINDOW_ID = "Trade Input Window"
TRADE_INPUT_INFO_WINDOW_SEARCH_BTN_ID = "Ticker Search Button"
TRADE_INPUT_INFO_WINDOW_ID = "Ticker Info"
TRADE_INPUT_ADD_BTN_ID = "Ticker Add"
TRADE_INPUT_RADIO_BTNS_ID = "Ticker Radio Buttons"
TRADE_INPUT_INFO_WINDOW_TICKER_ID = "Ticker Info Ticker"
TRADE_INPUT_INFO_WINDOW_COUNT_ID = "Ticker Info Count"
TRADE_INPUT_INFO_WINDOW_BOUGHT_PRICE_ID = "Ticker Info Bought Price"
TRADE_INPUT_INFO_WINDOW_REASON_ID = "Ticker Info Reason"
TRADE_INPUT_INFO_WINDOW_CONTRACT_BTN_ID = "Ticker Info Contract Button"
TRADE_INPUT_INFO_WINDOW_SHOW_CONTRACT_ID = "Ticker Info Show Contract"
TRADE_INPUT_INFO_WINDOW_CURRENT_PRICE_BTN_ID = "Ticker Info Current Price Button"
TRADE_INPUT_INFO_WINDOW_TICKER_TEXT_ID = "Trade Input Enter Ticker Text"

# ticker search window
TICKER_SEARCH_CRYPTO_STOCK_WINDOW_ID = "Ticker Search Crypto Stock"

# fintracker window
FINTRACKER_THEME_ID = "Fintracker Theme"
FINTRACKER_WINDOW_ID = "Fintracker Window"
FINTRACKER_CLOSED_TRADES_ID = "Fintracker Closed Trades"
FINTRACKER_OPEN_TRADES_ID = "Fintracker Open Trades"
FINTRACKER_OPEN_TRADES_BUTTONS_ID = "Fintracker Open Trades Buttons"
FINTRACKER_ADD_BTN_ID = "Fintracker Add Button"
FINTRACKER_NEWS_BTN_ID = "Fintracker News Button"
FINTRACKER_DISPLAY_WIN_RATE_ID = "Fintracker Win_Rate"
FINTRACKER_DISPLAY_TOTAL_PROFIT_ID = "Fintracker Profit"
FINTRACKER_OPEN_TRADES_CRYPTO_STOCK_TABLE_ID = "Fintracker Crypto Stock Open Trades Table"
FINTRACKER_OPEN_TRADES_OPTION_TABLE_ID = "Fintracker Options Open Trades Table"
FINTRACKER_OPEN_TRADES_CRYPTO_STOCK_TABLE_TEXT_ID = "Fintracker Stock Crypto Table Label"
FINTRACKER_OPEN_TRADES_OPTIONS_TABLE_TEXT_ID = "Fintracker Options Table Label"
FINTRACKER_CLOSED_TRADES_OPTION_TABLE_ID = "Fintracker Closed Trade Option Table"
FINTRACKER_CLOSED_TRADES_CRYPTO_STOCK_TABLE_ID = "Fintracker Closed Trade Stock Crypto Table"
FINTRACKER_CLOSED_OPEN_TRADES_GROUP_ID = "Fintracker Closed Open Trades Group"

# sell trade window
SELL_TRADE_WINDOW_ID = "Sell Trade Window"
SELL_TRADE_COUNT_ID = "Sell Trade Count"
SELL_TRADE_SOLD_PRICE_ID = "Sell Trade Sold Price"
SELL_TRADE_SELL_BTN_ID = "Sell Trade Sell Button"
SELL_TRADE_REASON_ID = "Sell Trade Reason"

# view trade window
VIEW_TRADE_WINDOW_ID = "View Trade ID"
VIEW_TRADE_TICKER_CONTRACT_ID = "View Trade Trade Input"
VIEW_TRADE_DATE_ID = "View Trade Date Input"
VIEW_TRADE_TYPE_ID = "View Trade Type Input"
VIEW_TRADE_COUNT_ID = "View Trade Count Input"
VIEW_TRADE_REASON_ID = "View Trade Reason Input"
VIEW_TRADE_BOUGHT_PRICE_ID = "View Trade Bought Price Input"
VIEW_TRADE_EDIT_BTN_ID = "View Trade Edit Button"
VIEW_TRADE_SAVE_BTN_ID = "View Trade Save Button"
VIEW_TRADE_CHANGE_CONTRACT_BTN_ID = "View Trade Choose Contract Button"
VIEW_TRADE_CANCEL_BTN_ID = "View Trade Cancel Button"
VIEW_TRADE_CHANGE_DATE_BTN_ID = "View Trade Change Date Button"
VIEW_TRADE_DATE_PICKER_ID = "View Trade Date Picker"
VIEW_TRADE_DATE_PICKER_WINDOW_ID = "View Trade Date Picker Window"
VIEW_TRADE_SOLD_PRICE_ID = "View Trade Sold Price"
VIEW_TRADE_NET_PROFIT_ID = "View Trade Net Profit"
VIEW_TRADE_PROFIT_PERCENTAGE_ID = "View Trade Profit Percentage"

# login window
LOGIN_THEME_ID = "Login Theme"
LOGIN_HEADER_ID = "Login Header"
LOGIN_WINDOW_ID = "Login Window"
LOGIN_INPUT_EMAIL_ID = "Login E-Mail"
LOGIN_INPUT_PASS_ID = "Login Password"
LOGIN_INPUT_BTN_ID = "Login Button"
LOGIN_REGISTER_BTN_ID = "Login_Register"
LOGIN_OFFLINE_BTN_ID = "Offline Mode"

# register window
REGISTER_THEME_ID = "Register Theme"
REGISTER_HEADER_ID = "Register Header"
REGISTER_WINDOW_ID = "Register Window"
REGISTER_INPUT_EMAIL_ID = "Register Email"
REGISTER_INPUT_PASS_ID = "Register Pass"
REGISTER_INPUT_ERROR_ID = "Register Error"
REGISTER_BTN_ID = "Register Button"
REGISTER_LOGIN_BTN_ID = "Register_Login"
REGISTER_INPUT_CONFIRM_PASS_ID = "Password Confirmation"

# value======================================================================
FINTRACKER_VIEWPORT_ICON_PATH = "resources/images/fintrack-logo.ico"
FINTRACKER_LOGO_PATH = "resources/images/fintracker-logo.png"
HOUR_IN_SECONDS = 3600 # used for refreshing tokens (login.py)
OSWALD_FONT_PATH = "resources/fonts/Oswald-VariableFont_wght.ttf"

NOT_APPLICABLE_TEXT = "N/A"
FONT_SCALE = 1.25
DEFAULT_DATE = {'month': date.today().month - 1,
                'year': date.today().year - 1900,
                'month_day': date.today().day}

LOST_CONNECTION_ERROR_MSG = "[Error] Lost Connection...Please Restart the App"
HTTPERROR_TEXT = "HTTPError"
CONNECTIONERROR_TEXT = "ConnectionError"

# validations
VALIDATE_ERROR_TYPE_MSG = "Invalid Type, has to be Crypto/Stock/Option"
VALIDATE_ERROR_COUNT_MSG = "Invalid Count (Can't be below 0)"
VALIDATE_ERROR_BOUGHT_PRICE_MSG = "Invalid Bought Price (Can't be below 0)"
VALIDATE_ERROR_INVALID_BOUGHT_PRICE_MSG = "Invalid Format (Valid: 4.53, 4.0, 3)"
VALIDATE_ERROR_STOCK_TICKER_MSG = "Invalid Ticker (Make sure spelling is correct)"
VALIDATE_ERROR_CRYPTO_TICKER_MSG = "Invalid Token (Type Full name like Bitcoin and use \'-\' for spaces)"
VALIDATE_ERROR_SOLD_PRICE_MSG = "Invalid Sold Price (Can't be below 0)"
VALIDATE_ERROR_CONTRACT_MSG = "No Contract was Chosen"

# height and width values
FINTRACKER_WINDOW_VIEWPORT_SIZE = (1700, 800)  # width x height

FINTRACKER_CLOSED_TRADES_VIEWPORT_SIZE = (FINTRACKER_WINDOW_VIEWPORT_SIZE[0] * 0.48,
                                          FINTRACKER_WINDOW_VIEWPORT_SIZE[1] * 0.65)
FINTRACKER_OPEN_TRADES_VIEWPORT_SIZE = (FINTRACKER_WINDOW_VIEWPORT_SIZE[0] * 0.48,
                                        FINTRACKER_WINDOW_VIEWPORT_SIZE[1] * 0.65)
FINTRACKER_OPEN_TRADES_BUTTONS_VIEWPORT_SIZE = (FINTRACKER_WINDOW_VIEWPORT_SIZE[0] * 0.45,
                                                FINTRACKER_WINDOW_VIEWPORT_SIZE[1] * 0.20)
FINTRACKER_DISPLAY_TOTAL_PROFIT_WIDTH = 200
FINTRACKER_DISPLAY_WIN_RATE_WIDTH = 200

LOGIN_WINDOW_VIEWPORT_SIZE = (FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 4,
                              FINTRACKER_WINDOW_VIEWPORT_SIZE[1] / 3)
LOGIN_WINDOW_POS_VALUE = [FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 2 - LOGIN_WINDOW_VIEWPORT_SIZE[0] / 2
    , FINTRACKER_WINDOW_VIEWPORT_SIZE[1] / 2 - LOGIN_WINDOW_VIEWPORT_SIZE[1] / 1.8]

REGISTER_WINDOW_VIEWPORT_SIZE = (FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 3.7,
                                 FINTRACKER_WINDOW_VIEWPORT_SIZE[1] / 2.3)
REGISTER_WINDOW_POS_VALUE = [FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 2 - REGISTER_WINDOW_VIEWPORT_SIZE[0] / 2
    , FINTRACKER_WINDOW_VIEWPORT_SIZE[1] / 2 - REGISTER_WINDOW_VIEWPORT_SIZE[1] / 2]

TRADE_INPUT_WINDOW_VIEWPORT_SIZE = (FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 2,
                                    FINTRACKER_WINDOW_VIEWPORT_SIZE[1] / 1.1)
TRADE_INPUT_INFO_WINDOW_VIEWPORT_SIZE = (FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 2.1,
                                         FINTRACKER_WINDOW_VIEWPORT_SIZE[1] / 1.5)
TRADE_INPUT_INFO_WINDOW_TICKER_WIDTH = FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 4
TRADE_INPUT_WINDOW_POS_VALUE = [FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 2 - TRADE_INPUT_WINDOW_VIEWPORT_SIZE[0] / 2
    , FINTRACKER_WINDOW_VIEWPORT_SIZE[1] / 2 - TRADE_INPUT_WINDOW_VIEWPORT_SIZE[1] / 1.9]

TICKER_SEARCH_WINDOW_VIEWPORT_SIZE = (FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 3,
                                      FINTRACKER_WINDOW_VIEWPORT_SIZE[1] / 1.5)
TICKER_SEARCH_WINDOW_POS = [FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 2 - TICKER_SEARCH_WINDOW_VIEWPORT_SIZE[0] / 2
    , FINTRACKER_WINDOW_VIEWPORT_SIZE[1] / 2 - TICKER_SEARCH_WINDOW_VIEWPORT_SIZE[1] / 1.9]

OPTIONS_WINDOW_VIEWPORT_SIZE = (FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 2,
                                FINTRACKER_WINDOW_VIEWPORT_SIZE[1] / 1.5)
OPTIONS_WINDOW_COMBO_WIDTH = FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 10
OPTIONS_WINDOW_POS = [FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 2 - OPTIONS_WINDOW_VIEWPORT_SIZE[0] / 2
    , FINTRACKER_WINDOW_VIEWPORT_SIZE[1] / 2 - OPTIONS_WINDOW_VIEWPORT_SIZE[1] / 1.9]

VIEW_TRADE_WINDOW_SIZE = (FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 2.3,
                          FINTRACKER_WINDOW_VIEWPORT_SIZE[1] / 1.6)

VIEW_TRADE_CHANGE_DATE_WINDOW_SIZE = (FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 6,
                                      FINTRACKER_WINDOW_VIEWPORT_SIZE[1] / 2.5)
VIEW_TRADE_WINDOW_POS = [FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 2 - VIEW_TRADE_WINDOW_SIZE[0] / 2
    , FINTRACKER_WINDOW_VIEWPORT_SIZE[1] / 2 - VIEW_TRADE_WINDOW_SIZE[1] / 1.9]
VIEW_TRADE_NETPROFIT_PROFITPER_WIDTH = 150
VIEW_TRADE_INPUT_FIELD_WIDTH = 250

SELL_TRADE_WINDOW_SIZE = (FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 5,
                          FINTRACKER_WINDOW_VIEWPORT_SIZE[1] / 2.7)
SELL_TRADE_WINDOW_POS = [FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 2 - SELL_TRADE_WINDOW_SIZE[0] / 2
    , FINTRACKER_WINDOW_VIEWPORT_SIZE[1] / 2 - SELL_TRADE_WINDOW_SIZE[1] / 1.9]

DIALOG_WINDOW_VIEWPORT_SIZE = (FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 4,
                               FINTRACKER_WINDOW_VIEWPORT_SIZE[1] / 4.5)
DIALOG_CENTER_WINDOW_POS = [FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 2 - DIALOG_WINDOW_VIEWPORT_SIZE[0] / 2
    , FINTRACKER_WINDOW_VIEWPORT_SIZE[1] / 2 - DIALOG_WINDOW_VIEWPORT_SIZE[1] / 2]
DIALOG_MESSAGE_WRAP_COUNT = 375

LOADING_WINDOW_VIEWPORT_SIZE = (FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 6,
                                FINTRACKER_WINDOW_VIEWPORT_SIZE[1] / 6.5)

LOADING_WINDOW_CENTER_WINDOW_POS = [FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 2 - LOADING_WINDOW_VIEWPORT_SIZE[0] / 2
    , FINTRACKER_WINDOW_VIEWPORT_SIZE[1] / 2 - LOADING_WINDOW_VIEWPORT_SIZE[1] / 2]

# dearpygui keywords
DPG_DATE_PICKER_YEAR = "year"
DPG_DATE_PICKER_MONTH = "month"
DPG_DATE_PICKER_DAY = "month_day"

# firebase keywords
FIREBASE_TOKENID = "idToken"
FIREBASE_REFRESHTOKEN = "refreshToken"
FIREBASE_DATE = "date"
FIREBASE_TICKER = "ticker"
FIREBASE_TYPE = "stock_type"
FIREBASE_COUNT = "count"
FIREBASE_BOUGHT_PRICE = "bought_price"
FIREBASE_REASON = "reason"
FIREBASE_CONTRACT = "contract"
FIREBASE_OPEN_TRADES = "Open Trades"
FIREBASE_CLOSE_TRADES = "Closed Trades"
FIREBASE_OPTION = "Options"
FIREBASE_STOCK_CRYPTO = "Stock_Crypto"
FIREBASE_LOCAL_ID = "localId"
FIREBASE_SOLD_PRICE = "sold_price"
FIREBASE_NET_PROFIT = "net_profit"
FIREBASE_PROFIT_PERCENTAGE = "profit_per"

# options keywords (used for creating dicts of contract objs)
OPTIONS_EXPIRATION_DATE = "expiry_date"
OPTIONS_TICKER = "option_ticker"
OPTIONS_TYPE = "option_type"
OPTIONS_STRIKE_PRICE = "strike_price"

# coingecko keywords
COINGECKO_SYMBOL = "symbol"
COINGECKO_NAME = "name"
COINGECKO_HASHINGALGO = "hashing_algorithm"
COINGECKO_CATEGORIES = "categories"
COINGECKO_DESC = "description"
COINGECKO_CURRENTPRICE = "current_price"
COINGECKO_CIRCULATINGSUPPLY = "circulating_supply"
COINGECKO_TOTALSUPPLY = "total_supply"
COINGECKO_MARKETCAP = "market_cap"
COINGECKO_MARKETDATA = "market_data"
COINGECKO_USD = "usd"
COINGECKO_ENGLISH = "en"
COINGECKO_PRICECHANGEPERCENT24H = "price_change_percentage_24h"

# yfinance keywords
YFINANCE_REGULARMARKETPRICE = "regularMarketPrice"
YFINANCE_STRIKE_PRICE = "strike"
YFINANCE_VOLUME = "volume"
YFINANCE_OPEN_INTEREST = "openInterest"
YFINANCE_IV_TEXT = "impliedVolatility"
YFINANCE_LONGBUSINESSSUMMARY = "longBusinessSummary"
YFINANCE_SHARESHORT = "sharesShort"
YFINANCE_SHARESHORTPRIORMONTH = "sharesShortPriorMonth"
YFINANCE_SHORTPERCENTFLOAT = "shortPercentOfFloat"
YFINANCE_MARKETCAP = "marketCap"
YFINANCE_SHORTNAME = "shortName"

# loading
LOADING_TEXT = "Loading...Please Wait"
LOADING_WINDOW_TEXT_SPACERY = LOADING_WINDOW_VIEWPORT_SIZE[1]/4
LOADING_WINDOW_TEXT_SPACERX = LOADING_WINDOW_VIEWPORT_SIZE[0]/5


# dialog
DIALOG_CONFIRMATION_BTN_TEXT = "Confirm"
DIALOG_SUCCESS_TEXT = "SUCCESS"

# options
OPTION_WINDOW_TEXT = "Choose Option Contract"
OPTION_CALL_TEXT = "Call"
OPTION_PUT_TEXT = "Put"
OPTION_WINDOW_TICKER_INPUT_TEXT = "Enter Ticker"
OPTION_WINDOW_SEARCH_CONTRACT_BTN_TEXT = "Search Contracts"
OPTION_STRIKE_LABEL_TEXT = "Strike Price"
OPTION_VOLUME_LABEL_TEXT = "Volume"
OPTION_OPEN_INTEREST_LABEL_TEXT = "Open Interest"
OPTION_IV_LABEL_TEXT = "Implied Volatility"
OPTION_SEARCH_BTN_TEXT = "Enter"
OPTION_INVALID_TICKER_MSG_TEXT = "[Error] Invalid Ticker / Ticker Doesn't Support Options"
OPTION_WINDOW_INPUT_SEARCH_GROUP_SPACERX = OPTIONS_WINDOW_VIEWPORT_SIZE[0] / 8.5
OPTION_WINDOW_COMBOS_GROUP_SPACERX = OPTIONS_WINDOW_VIEWPORT_SIZE[0] / 6

# trade input
TRADE_INPUT_THEME_ID = "Trade Input Theme"
TRADE_INPUT_WINDOW_TEXT = "Input Trade Info"
TRADE_INPUT_ADD_BTN_TEXT = "Add Trade"
TRADE_INPUT_INFO_WINDOW_SEARCH_BTN_TEXT = "Ticker Info"
TRADE_INPUT_INFO_WINDOW_SEARCH_BTN_TOOLTIP_TEXT = "Enter Ticker to Learn More About It"
TRADE_INPUT_INFO_WINDOW_TICKER_TEXT = "Enter Ticker:  "
TRADE_INPUT_INFO_WINDOW_REASON_TEXT = "(Optional) Enter your reason: "
TRADE_INPUT_INFO_WINDOW_CONTRACT_BTN_TEXT = "Choose Contract"
TRADE_INPUT_INFO_WINDOW_CURRENT_PRICE_BTN_TEXT = "Get Current Price"
TRADE_INPUT_INFO_WINDOW_CURRENT_PRICE_BTN_TOOLTIP_TEXT = "Get the Current Price of the Stock"
TRADE_INPUT_INFO_WINDOW_COUNT_TEXT = "Enter Count:   "
TRADE_INPUT_INFO_WINDOW_BOUGHT_PRICE_TEXT = "Bought Price: "
TRADE_INPUT_RADIO_BTN_CRYPTO_TEXT = "Crypto"
TRADE_INPUT_RADIO_BTN_STOCK_TEXT = "Stock"
TRADE_INPUT_RADIO_BTN_OPTION_TEXT = "Option"
TRADE_INPUT_INVALID_INPUT_MSG_TEXT = "[ERROR] Invalid Ticker (Crypto has to be full name) / Invalid Count \n / Invalid Bought Price"
TRADE_INPUT_TICKER_INPUT_EMPTY_MSG_TEXT = "[ERROR] Ticker Field is Empty"
TRADE_INPUT_INVALID_TICKER_MSG_TEXT = "[ERROR] Invalid Ticker"
TRADE_INPUT_INVALID_TOKEN_MSG_TEXT = "[ERROR] Invalid Token (Type Full Name i.e. Bitcoin, Cardano, etc...)"
TRADE_INPUT_SUCCESS_ADD_MSG_TEXT = "[SUCCESS] Successfully Added!"
TRADE_INPUT_CURRENT_PRICE_FAIL_MSG = "[ERROR] Could not get the price for the ticker (make sure spelling is correct)"
TRADE_INPUT_CURRENT_PRICE_EMPTY_FAIL_MSG = "[ERROR] Ticker Field can not be Empty"
TRADE_INPUT_RADIO_BTN_SPACERX = TRADE_INPUT_WINDOW_VIEWPORT_SIZE[0] / 3.5
TRADE_INPUT_TRADE_INFO_SPACERX = TRADE_INPUT_WINDOW_VIEWPORT_SIZE[0] / 3.5
TRADE_INPUT_REASON_INPT_SPACERY = 50
TRADE_INPUT_ADD_INFO_WIN_SPACERY = 50
TRADE_INPUT_ADD_BTN_SPACERX = TRADE_INPUT_WINDOW_VIEWPORT_SIZE[0] / 2.5
TRADE_INPUT_ADD_BTN_SPACERY = 50

# ticker search
TICKER_SEARCH_CRYPTO_STOCK_WINDOW_TEXT = "Search Crypto/Stock Info"
TICKER_SEARCH_TICKER_TEXT = "Ticker: "
TICKER_SEARCH_MARKET_CAP_STOCK_TEXT = "Market Cap: "
TICKER_SEARCH_SUMMARY_OF_BUSINESS_STOCK_TEXT = "Business Summary: "
TICKER_SEARCH_SHARES_SHORTED_STOCK_TEXT = "Shares Shorted: "
TICKER_SEARCH_SHARES_SHORTED_PRIOR_MONTH_TEXT = "Shares Shorted Prior Month: "
TICKER_SEARCH_SHORT_PERCENT_TEXT = "Short %: "
TICKER_SEARCH_CRYPTO_NAME_TEXT = "Token: "
TICKER_SEARCH_CRYPTO_HASHALGO_TEXT = "Hashing Algorithm: "
TICKER_SEARCH_CRYPTO_CATEGORIES_TEXT = "Category: "
TICKER_SEARCH_CRYPTO_DESCRIPTION_TEXT = "Description: "
TICKER_SEARCH_CRYPTO_CURPRICE_TEXT = "Current Price: "
TICKER_SEARCH_CRYPTO_CIRCSUPPLY_TEXT = "Circulating Supply: "
TICKER_SEARCH_CRYPTO_TOTSUPPLY_TEXT = "Total Supply: "
TICKER_SEARCH_CRYPTO_MRKTCAPTEXT = "Market Cap: "
TICKER_SEARCH_CHANGE_PERCENT_24H_TEXT = "24H Change %: "
TICKER_SEARCH_DESC_SPACERY = 20
TICKERS_SEARCH_WRAP_COUNT = 550

# fintracker
FINTRACKER_VIEWPORT_TITLE = "Fintracker - Record Your Trades!"
FINTRACKER_WINDOW_TEXT = "(Fintracker) Investment Tracker"
FINTRACKER_NEWS_BTN_TEXT = "News"
FINTRACKER_DISPLAY_TOTAL_PROFIT_TEXT = "Net Profit: "
FINTRACKER_DISPLAY_WIN_RATE_TEXT = "Win-Rate %: "
FINTRACKER_CLOSED_TRADES_TEXT = "Closed Trades"
FINTRACKER_OPEN_TRADES_TEXT = "Open Trades"
FINTRACKER_OPEN_TRADES_CRYPTO_STOCK_TABLE_TEXT = "Stock/Crypto"
FINTRACKER_OPEN_TRADES_OPTION_TABLE_TEXT = "Option"
FINTRACKER_VIEW_TRADE_BTN_TEXT = "View"
FINTRACKER_OPEN_TRADES_ROW_TEXT = "open_trade row "
FINTRACKER_CLOSED_TRADES_ROW_TEXT = "closed_trade row "
FINTRACKER_SELL_TEXT = "Sell"
FINTRACKER_REMOVE_TEXT = "X"
FINTRACKER_ADD_BTN_TEXT = "Add Trade"
FINTRACKER_MENU_SYSTEM_TEXT = "System"
FINTRACKER_MENU_LOGOUT_TEXT = "Logout"
FINTRACKER_MENU_EXIT_TEXT = "Exit App"
FINTRACKER_SELL_BTN_WIDTH = 90
FINTRACKER_VIEW_CLOSED_TRADE_BTN_WIDTH = 72
FINTRACKER_VIEW_OPEN_TRADE_BTN_WIDTH = 92
FINTRACKER_PROFIT_WINRATE_GROUP_SPACERY = 25
FINTRACKER_CLOSED_OPEN_TRADES_GROUP_SPACERY = 25
FINTRACKER_PROFIT_WINRATE_GROUP_SPACERX = FINTRACKER_WINDOW_VIEWPORT_SIZE[0] / 3.6
FINTRACKER_OPEN_REMOVE_SPACERX = 25
FINTRACKER_CLOSED_REMOVE_SPACERX = 15

# sell trade
SELL_TRADE_WINDOW_TEXT = "Selling Trade"
SELL_TRADE_COUNT_TEXT = "Number Sold: "
SELL_TRADE_SOLD_PRICE_TEXT = "Sold Price:     "
SELL_TRADE_SELL_BTN_TEXT = "Sell Trade"
SELL_TRADE_REASON_TEXT = "Reason:          "
SELL_TRADE_SOLD_SUCCESS_MSG_TEXT = "[SUCCESS] Trade Sold Successfully"
SELL_TRADE_INVALID_INPUT_MSG_TEXT = "[ERROR] Invalid Sold Count / Invalid Sold Price/ Lost Connection"
SELL_TRADE_SELL_BTN_SPACERX = SELL_TRADE_WINDOW_SIZE[0] / 3
SELL_TRADE_SELL_BTN_SPACERY = 10
SELL_TRADE_WINDOW_SPACERY = 10

# view trade
VIEW_TRADE_WINDOW_TEXT = "View Trade"
VIEW_TRADE_EDIT_BTN_TEXT = "Edit Trade"
VIEW_TRADE_SAVE_BTN_TEXT = "Apply Changes"
VIEW_TRADE_CHANGE_CONTRACT_BTN_TEXT = "Change Contract"
VIEW_TRADE_TICKER_CONTRACT_TEXT = "Trade:            "
VIEW_TRADE_DATE_TEXT = "DOP:          "
VIEW_TRADE_DATE_TOOLTIP_TEXT = "Date of Purchase"
VIEW_TRADE_TYPE_TEXT = "Type:              "
VIEW_TRADE_COUNT_TEXT = "Count:        "
VIEW_TRADE_BOUGHT_PRICE_TEXT = "Bought Price:"
VIEW_TRADE_REASON_TEXT = "Reason:         "
VIEW_TRADE_CANCEL_BTN_TEXT = "Cancel"
VIEW_TRADE_CHANGE_DATE_BTN_TEXT = "Change Date"
VIEW_TRADE_DATE_PICKER_WINDOW_TEXT = "Choose Date"
VIEW_TRADE_SOLD_PRICE_TEXT = "Sold Price:"
VIEW_TRADE_NET_PROFIT_TEXT = "Net Profit:     "
VIEW_TRADE_PROFIT_PERCENTAGE_TEXT = "Profit %:   "
VIEW_TRADE_SUCCESS_EDIT_MSG_TEXT = "[SUCCESS] Updated Trade!"
VIEW_TRADE_SPACERX = 15
VIEW_TRADE_SPACERY = 5
VIEW_TRADE_SAVE_CANCEL_BTNS_SPACERX = VIEW_TRADE_WINDOW_SIZE[0] / 2.5
VIEW_TRADE_CHANGE_BTNS_SPACERX = VIEW_TRADE_WINDOW_SIZE[0] / 2.7
VIEW_TRADE_CHANGE_DATE_SPACERX = VIEW_TRADE_WINDOW_SIZE[0] / 2.2
VIEW_TRADE_EDIT_BTN_SPACERX = VIEW_TRADE_WINDOW_SIZE[0] / 2.2

# login
LOGIN_HEADER_TEXT = "Fintracker | Login"
LOGIN_FAILED_MSG_TEXT = "[ERROR] Invalid Login Credentials"
LOGIN_INPUT_EMAIL_TEXT = "Enter E-Mail"
LOGIN_INPUT_PASS_TEXT = "Enter Password"
LOGIN_INPUT_BTN_TEXT = "Login"
LOGIN_REGISTER_BTN_TEXT = "Not a user? Sign up now!"
LOGIN_OFFLINE_BTN_TEXT = "Offline Mode"
LOGIN_SUCCESSFUL_MSG_TEXT = "[SUCCESS] Logged in Successfully"

# register
REGISTER_SPACERX_VALUE = 45
REGISTER_SPACERY_VALUE = 3
REGISTER_HEADER_TEXT = "Fintracker | Register"
REGISTER_INPUT_EMAIL_TEXT = "Enter E-Mail"
REGISTER_INPUT_PASS_TEXT = "Enter Password"
REGISTER_SUCCESS_MSG_TEXT = "[SUCCESS] Registered new account! Thank You."
REGISTER_FAILED_MSG_TEXT = "[ERROR] E-Mail is currently being used and/or Confirm Password and Password are not the " \
                           "same."
REGISTER_BTN_TEXT = "Register"
REGISTER_LOGIN_BTN_TEXT = "Sign-In"
REGISTER_INPUT_CONFIRM_PASS_TEXT = "Confirm Password"
